# Generated by Django 4.0.1 on 2022-01-26 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_remove_category_published_category_is_active'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='EventCategory',
        ),
    ]
