# Generated by Django 4.0.1 on 2022-02-02 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0004_region_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Назва події')),
                ('description', models.TextField(max_length=1024, verbose_name='Детальний опис події')),
                ('date_start', models.DateTimeField(verbose_name='Дата початку події')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершення події')),
                ('format', models.CharField(choices=[('Онлайн', 'online'), ('Оффлайн', 'offline'), ('Змішаний', 'online-offline')], default='online', max_length=24, verbose_name='Формат проведення події')),
                ('auto_confirmation', models.BooleanField(default=False, verbose_name='Автоматично підтверджувати участь в події?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна/неактивна')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення події')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата останнього оновлення інформації')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_in_category', to='event.eventcategory', verbose_name='Категорія')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_in_city', to='event.city', verbose_name='Місто')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL, verbose_name='Організатор')),
            ],
            options={
                'verbose_name': 'Подія',
                'verbose_name_plural': 'Події',
            },
        ),
        migrations.CreateModel(
            name='EventSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Instagram', 'instagram'), ('Facebook', 'facebook'), ('Linkedin', 'linkedin'), ('Wedsite', 'website'), ('Other', 'other')], default='other', max_length=16, verbose_name='Тип соціальної мережі')),
                ('link', models.URLField(verbose_name='Посилання на соціальні мережі')),
            ],
            options={
                'verbose_name': 'Соціальна мережа',
                'verbose_name_plural': 'Населені пункти',
            },
        ),
        migrations.CreateModel(
            name='EventSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Участь в події підтверджена організатором?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення події')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='event.event', verbose_name='Подія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Підписник')),
            ],
            options={
                'verbose_name': 'Учасник події',
                'verbose_name_plural': 'Учасники події',
            },
        ),
        migrations.AddField(
            model_name='event',
            name='social_link',
            field=models.ManyToManyField(blank=True, related_name='event', to='event.EventSocialLink', verbose_name='Посилання на соцмережі'),
        ),
    ]
