# Generated by Django 4.0.1 on 2022-02-03 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_event_eventsociallink_eventsubscriber_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventsociallink',
            options={'verbose_name': 'Соціальна мережа', 'verbose_name_plural': 'Соціальні мережі, які прикріплені до подій'},
        ),
        migrations.AlterModelOptions(
            name='eventsubscriber',
            options={'verbose_name': 'Учасник події', 'verbose_name_plural': 'Учасники подій'},
        ),
    ]
