# Generated by Django 4.0.1 on 2022-02-09 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_event_city_delete_city_delete_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='social_link',
        ),
        migrations.AddField(
            model_name='eventsociallink',
            name='event',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='social_link', to='event.event', verbose_name='Подія'),
            preserve_default=False,
        ),
    ]
