# Generated by Django 4.0.1 on 2022-02-09 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_remove_event_social_link_eventsociallink_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='format',
            field=models.CharField(choices=[('online', 'Онлайн'), ('offline', 'Оффлайн'), ('online-offline', 'Змішаний')], default='online', max_length=24, verbose_name='Формат проведення події'),
        ),
    ]
