# Generated by Django 4.0.1 on 2022-02-09 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_event_format'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='format',
            new_name='event_format',
        ),
    ]
