# Generated by Django 4.0.1 on 2022-02-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_rename_format_event_event_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsociallink',
            name='type',
            field=models.CharField(choices=[('instagram', 'instagram'), ('facebook', 'facebook'), ('linkedin', 'linkedin'), ('wedsite', 'website'), ('other', 'other')], default='other', max_length=16, verbose_name='Тип соціальної мережі'),
        ),
    ]
