# Generated by Django 4.0.1 on 2022-02-11 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_alter_eventsociallink_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventSubscriber',
        ),
    ]
