# Generated by Django 4.0.1 on 2022-02-11 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0012_delete_eventsubscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation', models.BooleanField(default=False, verbose_name='Участь в події підтверджена організатором?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення події')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='event.event', verbose_name='Подія')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_subscribe', to=settings.AUTH_USER_MODEL, verbose_name='Підписник')),
            ],
            options={
                'verbose_name': 'Учасник події',
                'verbose_name_plural': 'Учасники подій',
            },
        ),
    ]
