# Generated by Django 4.0.1 on 2022-01-17 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernew',
            name='gender',
            field=models.CharField(choices=[('man', 'Чоловіча'), ('female', 'Жіноча')], default=1, max_length=16, verbose_name='Стать'),
            preserve_default=False,
        ),
    ]
