# Generated by Django 4.0.1 on 2022-01-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_usernew_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernew',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True, verbose_name='Номер телефону'),
        ),
    ]
